# Generated by Django 4.1.1 on 2022-09-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_create_at_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_on_sale',
            field=models.BooleanField(default=True),
        ),
    ]
