# Generated by Django 4.1.1 on 2022-09-15 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_is_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
    ]
